spring:
  application:
    name: location
  datasource:
      url: jdbc:mysql://localhost:3306/location_db
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    root: error
    com.ocprojecttree.location: info
server:
  servlet:
    context: /api


